server:
  port: 8081

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/microticket?useSSL=false&allowPublicKeyRetrieval=true&useUnicode=true&characterEncoding=utf8&serverTimezone=Asia/Shanghai"
    username: root
    password: 123456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Shanghai

  redis:
    host: localhost
    port: 6379

wechat:
  appid: your_appid_here
  secret: your_secret_here
  mchId: your_mch_id
  apiKey: your_api_key
  notifyUrl: https://yourdomain.com/api/payments/notify

jwt:
  secret: verySecretJwtKey
  expireSeconds: 86400
